### ISSUE TITLE
camera found, but catching error "CAN'T CONNECT TO CAMERA :("

### ISSUE THREAD

**Issue by FabianPP** [inspirit/GPUImage#6]
catch (err:Error)
            {
                //_txt.text = "CAN'T CONNECT TO CAMERA :(";
            }

do you have any suggestion what could be the problem?
when I set RenderMode to Direct, it runs with webcam on Desktop.

Tested with AIR 3.9 and 4.0

**Comment by inspirit** [comment]
well u better ask it at ADOBE/AIR forums.
GPUImage doesn't do anything with camera it just works with the image.
